server:
  port: 8090
spring:
  application:
    name: order-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
        username: nacos
        password: nacos
        namespace: public
    gateway:
      #路由规则
      routes:
        - id: order-route #路由唯一标识
          uri: lb://order-ribbon
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1 #转发之前去掉第一层路径

    sentinel:
      transport:
        dashboard: 127.0.0.1:8859