server:
  port: 8060
spring:
  application:
    name: order-nacos-config
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
        username: nacos
        password: nacos
        namespace: public
      config:
        server-addr: 127.0.0.1:8849
        username: nacos
        password: nacos
        namespace: public
        file-extension: yml